title: Audiveris Pages
author: Hervé Bitteur
#email: your-email@domain.com

#  description:
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  Content of Audiveris pages.
  Beginning with 5.1 release, it should provide handbook,
  documented OMR file format and link to Javadoc.

# social links
#twitter_username: your-twitter-handle
github_username:  hbitteur

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
